services:
  # Frontend React Application
  frontend:
    build: ./frontend
    container_name: fashion-frontend
    ports:
      - "3000:80"
    depends_on:
      - eep
    volumes:
      - ./eep/static:/usr/share/nginx/html/static

  # External Endpoint Processor
  eep:
    build: ./eep
    container_name: fashion-eep
    ports:
      - "7000:9000"
    volumes:
      - ./eep:/app
      - ./eep/static:/app/static
    depends_on:
      - detection-iep
      - style-iep
      - feature-iep
      - virtual-tryon-iep
      - elegance-iep
      - reco-data-iep
      - match-iep
      - text2image-iep
    environment:
      - DETECTION_SERVICE_URL=http://detection-iep:8001
      - STYLE_SERVICE_URL=http://style-iep:8002
      - FEATURE_SERVICE_URL=http://feature-iep:8003
      - VIRTUAL_TRYON_SERVICE_URL=http://virtual-tryon-iep:8004
      - ELEGANCE_SERVICE_URL=http://elegance-iep:8005
      - RECO_DATA_SERVICE_URL=http://reco-data-iep:8007
      - MATCH_SERVICE_URL=http://match-iep:8008
      - TEXT2IMAGE_SERVICE_URL=http://text2image-iep:8020
      - SERVICE_TIMEOUT=60

  # Detection Internal Endpoint Processor
  detection-iep:
    build: ./detection_iep
    container_name: detection-iep
    ports:
      - "7001:8001"
    volumes:
      - ./detection_iep:/app
      - ./yolov8_clothing_detection_segmentation.pt:/app/models/yolov8_clothing_detection_segmentation.pt
    environment:
      - MODEL_PATH=/app/models/yolov8_clothing_detection_segmentation.pt
      - CONFIDENCE_THRESHOLD=0.55

  # Style Classification Internal Endpoint Processor
  style-iep:
    build: ./style_iep
    container_name: style-iep
    ports:
      - "7002:8002"
    volumes:
      - ./style_iep:/app
      - ./yolov8_style_model.pt:/app/models/yolov8_style_model.pt
    environment:
      - MODEL_PATH=/app/models/yolov8_style_model.pt
      - CONFIDENCE_THRESHOLD=0.3

  # Feature Extraction Internal Endpoint Processor
  feature-iep:
    build: ./feature_iep
    container_name: feature-iep
    ports:
      - "7003:8003"
    volumes:
      - ./feature_iep:/app
      - ./multitask_resnet50_finetuned.pt:/app/models/multitask_resnet50_finetuned.pt
    environment:
      - MODEL_PATH=/app/models/multitask_resnet50_finetuned.pt
      
  # Virtual Try-On Internal Endpoint Processor
  virtual-tryon-iep:
    build: ./virtual_tryon_iep
    container_name: virtual-tryon-iep
    ports:
      - "7004:8004"
    volumes:
      - type: bind
        source: ./virtual_tryon_iep
        target: /app
      - type: bind
        source: ./virtual_tryon_iep/static
        target: /app/static
    environment:
      - FASHN_AI_API_KEY=${FASHN_AI_API_KEY}
      - FASHN_AI_BASE_URL=${FASHN_AI_BASE_URL}

  # Elegance Chatbot Internal Endpoint Processor
  elegance-iep:
    build: ./elegance_iep
    container_name: elegance-iep
    ports:
      - "7005:8005"
    volumes:
      - ./elegance_iep:/app
      - ./elegance_iep/static:/app/static
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
  # Recommendation Data Internal Endpoint Processor
  reco-data-iep:
    build: ./reco_data_iep
    container_name: reco-data-iep
    ports:
      - "7007:8007"
    volumes:
      - ./reco_data_iep:/app
      - ./reco_data_iep/ca.pem:/app/ca.pem
      - ./reco_data_iep/auradataset-643b5a8d654e.json:/app/auradataset-643b5a8d654e.json
    env_file:
      - ./reco_data_iep/.env 
      
  # Match Analysis Internal Endpoint Processor
  match-iep:
    build: ./match_iep
    container_name: match-iep
    ports:
      - "7008:8008"
    volumes:
      - ./match_iep:/app
    environment:
      - SERVICE_TIMEOUT=30
      
  # Text to Image Internal Endpoint Processor  
  text2image-iep:
    build: ./text2image_iep
    container_name: text2image-iep
    ports:
      - "7020:8020"
    volumes:
      - ./text2image_iep:/app
      - ./text2image_iep/auradataset-643b5a8d654e.json:/app/auradataset-643b5a8d654e.json
    env_file:
      - ./text2image_iep/.env 