{
 "title": "Fashion Services Dashboard",
 "tags": [
  "fashion",
  "microservices"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fashion Microservices Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fashion-services\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Fashion Service Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (container_memory_usage_bytes{name=~\"fashion-.*|.*-iep\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fashion Service CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=~\"fashion-.*|.*-iep\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fashion Service Network Input",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_receive_bytes_total{name=~\"fashion-.*|.*-iep\"}[1m]))",
     "legendFormat": "{{name}} - RX"
    }
   ]
  },
  {
   "title": "Fashion Service Network Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_transmit_bytes_total{name=~\"fashion-.*|.*-iep\"}[1m]))",
     "legendFormat": "{{name}} - TX"
    }
   ]
  }
 ]
}