global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fashion-eep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['eep:9000']
        labels:
          service: 'eep'
          instance: 'fashion-eep'

  - job_name: 'detection-iep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['detection-iep:8001']
        labels:
          service: 'detection'
          instance: 'detection-iep'

  - job_name: 'style-iep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['style-iep:8002']
        labels:
          service: 'style'
          instance: 'style-iep'

  - job_name: 'feature-iep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['feature-iep:8003']
        labels:
          service: 'feature'
          instance: 'feature-iep'
          
  - job_name: 'virtual-tryon-iep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['virtual-tryon-iep:8004']
        labels:
          service: 'virtual-tryon'
          instance: 'virtual-tryon-iep'
          
  - job_name: 'elegance-iep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['elegance-iep:8005']
        labels:
          service: 'elegance'
          instance: 'elegance-iep'
          
  - job_name: 'match-iep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['match-iep:8008']
        labels:
          service: 'match'
          instance: 'match-iep'
          
  - job_name: 'reco-data-iep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['reco-data-iep:8007']
        labels:
          service: 'reco-data'
          instance: 'reco-data-iep'
          
  - job_name: 'text2image-iep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['text2image-iep:8020']
        labels:
          service: 'text2image'
          instance: 'text2image-iep'
          
  - job_name: 'ppl-detector-iep'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ppl-detector-iep:8009']
        labels:
          service: 'ppl-detector'
          instance: 'ppl-detector-iep'

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100'] 