global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Fashion App Backend Services
  - job_name: 'fashion-app-services'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:7000']
        labels:
          service: 'eep'
      - targets: ['host.docker.internal:7001']
        labels:
          service: 'detection-iep'
      - targets: ['host.docker.internal:7002']
        labels:
          service: 'style-iep'
      - targets: ['host.docker.internal:7003']
        labels:
          service: 'feature-iep'
      - targets: ['host.docker.internal:7004']
        labels:
          service: 'virtual-tryon-iep'
      - targets: ['host.docker.internal:7005']
        labels:
          service: 'elegance-iep'
      - targets: ['host.docker.internal:7007']
        labels:
          service: 'reco-data-iep'
      - targets: ['host.docker.internal:7008']
        labels:
          service: 'match-iep'
      - targets: ['host.docker.internal:7020']
        labels:
          service: 'text2image-iep'
      - targets: ['host.docker.internal:7009']
        labels:
          service: 'ppl-detector-iep'

  # Frontend monitoring
  - job_name: 'frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'frontend' 